In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#creating "tensor" array using Numpy
numpy_tensor = np.array([[3,4],[5,6]])
#printing array
print(numpy_tensor)
#applying operations (addition/multiplication/reshape) and printing results 
np_tensor_add = numpy_tensor + 4
np_tensor_multiply = numpy_tensor * 5
np_tensor_reshape = numpy_tensor.reshape(4,1)
print('NP tensor foolowing the addition:', np_tensor_add)
print('NP tensor foolowing the multiplication:', np_tensor_multiply)
print('NP tensor foolowing the reshape:', np_tensor_reshape)

[[3 4]
 [5 6]]
NP tensor foolowing the addition: [[ 7  8]
 [ 9 10]]
NP tensor foolowing the multiplication: [[15 20]
 [25 30]]
NP tensor foolowing the reshape: [[3]
 [4]
 [5]
 [6]]


In [3]:
#creating tensor using TensorFlow
tf_tensor = tf.constant([[7,8],[9,10]])
#printing tensor
print(tf_tensor)
#applying operations (addition/multiplication/reshape) and printing results
tf_tensor_add = tf_tensor + 4
tf_tensor_multiply = tf_tensor * 5
tf_tensor_reshape = tf.reshape(tf_tensor, [4,1])
print('TF tensor foolowing the addition:', tf_tensor_add)
print('TF tensor foolowing the multiplication:', tf_tensor_multiply)
print('TF tensor foolowing the reshape:', tf_tensor_reshape)

tf.Tensor(
[[ 7  8]
 [ 9 10]], shape=(2, 2), dtype=int32)
TF tensor foolowing the addition: tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
TF tensor foolowing the multiplication: tf.Tensor(
[[35 40]
 [45 50]], shape=(2, 2), dtype=int32)
TF tensor foolowing the reshape: tf.Tensor(
[[ 7]
 [ 8]
 [ 9]
 [10]], shape=(4, 1), dtype=int32)


In [4]:
#TensorFlow GradientTape function allows the calculation of a gradients, which is useful for backpropagation in neural networks. With NumPy the gradient can be found by implementing it manually.

x_np = np.array(3.0)
y_np = x_np * x_np
# Compute the gradient manually
dy_dx_np = 2 * x_np
print("Gradient of y with respect to x (NumPy):", dy_dx_np)

#computing gradient with TensorFlow GradientTape 
x_tf = tf.constant(3.0)

with tf.GradientTape() as tape:
    tape.watch(x_tf)
    y_tf = x_tf * x_tf

dy_dx_tf = tape.gradient(y_tf, x_tf)
print("Gradient of y with respect to x (TensorFlow):", dy_dx_tf)

Gradient of y with respect to x (NumPy): 6.0
Gradient of y with respect to x (TensorFlow): tf.Tensor(6.0, shape=(), dtype=float32)


In [6]:
#Eager execution allows for operations to be executed immediatly which is very convenient. This is how NumPy arrays typically operate. But TensorFlow also has the option to turn off Eager execution which NumPy does not. 

#attempting eager execution with Python lists results in an error because python does not allow the multiplication of two lists but it does work with NumPy.
x2 = np.array([3])

x = [3.0]
try:
    y = x2 * x2
    print("Eager execution with regular tensor:", y)
except Exception as e:
    print("Error with regular tensor:", e)

#with Eager execution enabled the tensor can be multiplied by itself resulting in the operation product
tf.config.run_functions_eagerly(True)

x = tf.constant(3.0)
y = x * x
print("Eager execution with TensorFlow tensor:", y)

#with Eager execution turned off the operations can only be completed with in a session, after TensorFlow builds a computational graph
tf.compat.v1.disable_eager_execution()

x = tf.constant([3.0])
y = x * x

#creating session to run operations
with tf.compat.v1.Session() as sess:
    result = sess.run(y)
    print("TensorFlow without eager execution:", result)

Eager execution with regular tensor: [9]
Eager execution with TensorFlow tensor: tf.Tensor(9.0, shape=(), dtype=float32)
TensorFlow without eager execution: [9.]


In [5]:
#TensorFlow Ragged Tensor allows the creation of tensors that can represent irregular shapes. Something similar can be achieved with nested lists but these do not allow operations to be performed.
#TensorFlow Ragged Tensor creation
rt1 = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
rt2 = tf.ragged.constant([[10, 20, 30], [40, 50], [60]])

#performing element-wise addition
rt_sum = rt1 + rt2
print("TensorFlow Ragged Tensor addition:")
print(rt_sum)

#Ragged lists made using python nested lists
ragged_list1 = [[1, 2, 3], [4, 5], [6]]
ragged_list2 = [[10, 20, 30], [40, 50], [60]]

#performing element-wise addition manually
ragged_list_sum = [[a + b for a, b in zip(sublist1, sublist2)] 
                   for sublist1, sublist2 in zip(ragged_list1, ragged_list2)]

print("Python Nested Lists addition:")
print(ragged_list_sum)

#manipulation with Ragged Tensor is far more convenient and easier to implement than doing so with pythons built in nested lists. 

TensorFlow Ragged Tensor addition:
<tf.RaggedTensor [[11, 22, 33], [44, 55], [66]]>
Python Nested Lists addition:
[[11, 22, 33], [44, 55], [66]]


Part 4: Comparison and Explanation

On the very surface regular NumPy arrays and TensorFlow tensors are quite similar. That being said there are some key differences that make TensorFlow tensors more suitable for complex computations, especially in machine learning and more specifically deep learning.

A NumPy array and TensorFlow tensor are similar in that they both can store and manipulate multidimensional data. However, TensorFlow tensors are designed for building computational graphs, which is an abstraction defined by the flow of operations on the data. These computational graphs allow for more complex and multi-step compuations. NumPy arrays are used more generally for numerical computations.

TensorFlow tensors can enable the use of GPUs (graphics processing units) for faster computations compared to NumPy arrays, which are typically CPU-bound. The TensorFlow tensor is stored in the GPU memory while the NumPy array is stored in the local memory of the computer. This makes tensors more powerful when applied in deep learning because larger and deeper networks can be trainer quicker through GPU operations than standard NumPy arrays.

In general, TensorFlow tensors offer a quicker and more flexible framework for complex numerical computations, which are needed when training machine learning algorithms on a large amount of data. 